export enum ExceptionCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERNAME_ALREADY_USED = 'USERNAME_ALREADY_USED',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  EMAIL_TOKEN_INVALID = 'EMAIL_TOKEN_INVALID',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  ALREADY_LINKED = 'ALREADY_LINKED',
  NO_REMAINING_AUTH = 'NO_REMAINING_AUTH',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_MISMATCH = 'REFRESH_TOKEN_MISMATCH',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_SAVE_FAILED = 'REFRESH_TOKEN_SAVE_FAILED',
}
